// Copyright 2026 CloudSmith Contributors
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json.Serialization;

namespace CloudSmith.Relay.Messages;

/// <summary>
/// Discriminated union of every message flowing across the Relay -> PaaS
/// WebSocket. Polymorphism is wire-encoded via the <c>$type</c> JSON discriminator.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(JobDispatch), typeDiscriminator: "job.dispatch")]
[JsonDerivedType(typeof(JobAck), typeDiscriminator: "job.ack")]
[JsonDerivedType(typeof(InventoryPush), typeDiscriminator: "inventory.push")]
[JsonDerivedType(typeof(HealthProbePush), typeDiscriminator: "health.push")]
[JsonDerivedType(typeof(HardwarePush), typeDiscriminator: "hardware.push")]
[JsonDerivedType(typeof(Heartbeat), typeDiscriminator: "heartbeat")]
public abstract record RelayMessage;

/// <summary>
/// PaaS -> Relay: dispatch a job for execution against an Agent or via PSRemote.
/// Canonical shape per the frozen job dispatch contract (AB#4839).
/// </summary>
/// <param name="JobId">Primary key of the core.jobs row. Generated by the API.</param>
/// <param name="JobType">Logical operation identifier, e.g. <c>cluster.validate-network</c>.</param>
/// <param name="PayloadJson">
/// Opaque JSON string — the dispatch pipeline never interprets it; only the
/// executing target parses it.
/// </param>
/// <param name="IdempotencyKey">Client-supplied dedupe key (nullable).</param>
/// <param name="Traceparent">W3C trace context, propagated end-to-end (nullable).</param>
public sealed record JobDispatch(
    Guid JobId,
    string JobType,
    string PayloadJson,
    string? IdempotencyKey = null,
    string? Traceparent = null) : RelayMessage;

/// <summary>
/// Relay -> PaaS: acknowledge a JobDispatch. Sent only after the job is durably
/// persisted to the Relay's local queue (contract §6.2).
/// </summary>
/// <param name="JobId">Echoes the dispatch.</param>
/// <param name="AckStatus"><c>accepted</c> | <c>rejected</c> | <c>duplicate</c>.</param>
/// <param name="Detail">Reason detail when <paramref name="AckStatus"/> is <c>rejected</c>.</param>
public sealed record JobAck(
    Guid JobId,
    string AckStatus,
    string? Detail = null) : RelayMessage;

/// <summary>Relay -> PaaS: bulk inventory push for a managed cluster.</summary>
public sealed record InventoryPush(
    string ClusterId,
    IReadOnlyList<VmSnapshot> Vms) : RelayMessage;

/// <summary>Relay -> PaaS: cluster-level health probe results.</summary>
public sealed record HealthProbePush(
    string ClusterId,
    string Status,
    IReadOnlyList<HealthCheck> Checks) : RelayMessage;

/// <summary>Relay -> PaaS: host hardware snapshot.</summary>
public sealed record HardwarePush(
    string HostId,
    int ProcessorCount,
    int LogicalCoreCount,
    string? ProcessorName,
    long TotalMemoryBytes,
    DateTimeOffset ObservedAtUtc) : RelayMessage;

/// <summary>Relay -> PaaS: liveness heartbeat.</summary>
/// <param name="At">UTC timestamp when the heartbeat was sent.</param>
/// <param name="SiteId">
/// Optional site identifier — echoed back on every heartbeat so PaaS can correlate
/// relay status to the correct site even if registration state is lost.
/// </param>
public sealed record Heartbeat(DateTimeOffset At, string? SiteId = null) : RelayMessage;

/// <summary>
/// Async event-handler signature used by <see cref="Connection.IRelayConnection.OnMessageReceived"/>.
/// </summary>
public delegate Task AsyncEventHandler<T>(object sender, T args);
